### ISSUE TITLE
Errorneous syntax highlighting

### ISSUE THREAD

**Issue by japro** [vbmacher/emuStudio#106]
Syntax highlighting does not work correctly.

**Comment by vbmacher** [comment]
Do not close this issue yet, the solution must be better.

**Comment by vbmacher** [comment]
What actually happened is that when you typed instructions letter-by-letter, each letter itself was not recognized and therefore marked as `ERROR` token. Compiler should work without problem. The problem was only in the syntax highlighter, in main module of emuStudio.

It was related to how the syntax highlighter works. It is designed to be efficient. When the text changes in the document, it re-colors only the minimum part which is required to recolor, and leave the rest as-is.

Determining the "minimum part" is based on an idea of finding the first token with initial state which is to the left of the change. The highlighter manages the initial-state tokens set, which is empty in the beginning.

Token in the initial lex. state represents a "safe" start of the recoloring, because otherwise (like in the middle of a string) we would not start recoloring from the beginning of the "sentence". From this token position, the lexer is called, asking for the next symbol which is recolored in the document. If the symbol is in initial state, it is added to the original set of the initial-state tokens.

This process is happening either until the end of the document, or until a token is found which has already good color. This is determined that the token returned by the lexer is the same (including its position) as the token which is already in the initial-state tokens set.
 
And now watch what happened here:

1. pressed `l`, token was `ERROR`, initial-state tokens set now contains pair `(0, ERROR)`
2. pressed `d`, highlighter found initial-state token at position `0`, and starts highlighting at position `1`. The `d` is added to the initial-state tokens set as pair `(1, ERROR)`
3. pressed `n`, again - highlighter found initial token at position `1` and starts highlighting at `2`. Now the initial-state tokens set contains pairs: `[(0,ERROR), (1,ERROR), (2, ERROR)]` 

*Solution*

The solution was to not consider `ERROR` tokens as "initial tokens" (tokens with initial lexical state). The implication is that the highlighter will not restart highlighting after an `ERROR` token.

Proof:

1. pressed `l`, initial-state tokens set = `[]` (empty - the error was not added to the set)
2. pressed `d`, highlighter starts again at `0`, now the lexer considers text `ld`, which is again `ERROR`, but it is not added to the initial-state tokens set.
3. pressed `n`, highlighter starts again at `0` (because initial-state tokens set is empty), so the lexer considers text `ldn` which it now recognizes as a reserved word. Initial-state tokens set now contains `[(4, RESERVED)]`, and everything is working as expected.
